### ISSUE TITLE
Assignment 1: Problem Statement

### ISSUE THREAD

**Issue by pop** [XZES40/CS-Capstone-Project#1]
Our first assignment is October Friday October 14, printed and signed by us and our client.  A rough draft of the Abstract (point 1) is due October 6.  The assignment can be found on the CS Capstone website, but the main bullet points are:
- **Project abstract**, with a concise introduction to the problem you are trying to solve and your proposed solution.
- **Problem definition**, with a description of the problem you are trying to solve.
- **Proposed solution**: What is your solution going to be able to do? How does this meet the needs of the problem? What do you think you will show at Expo? Exact details not necessary, but you should have a high level view of what will be presented.
- **Performance metrics**: How will you measure whether or not your solution meets your defined needs and functions well?

Below are the components of this assignment which need to be completed:
- Rough Draft
  - [x] Abstract
  - [ ] Problem Definition
  - [ ] Proposed Solution
  - [ ] Performance Metrics
- Final Draft
  - [ ] Abstract
  - [ ] Problem Definition
  - [ ] Proposed Solution
  - [ ] Performance Metrics
- [ ] Signed Copy

I have already created a skeleton of this document in the repository.  Contribute to this by creating a branch on the repository, making changes on that branch, and creating a Pull Request.  Reference this issue in the Pull Request description.

The documents you need to fill out are in the `sections` directory of the repository and they are included in the assignment document with the `\include{...}` LateX directive.  Edits top the documents in the `sections` directory show up in the final document.

Run `make` in a terminal in the repository to build the PDF.  This works on all Oregon State University Linux workstations and the servers on `access.engr.oregonstate.edu`. Read the README for more information.

**Comment by todouu** [comment]
only the abstract will due tomorrow, right?

**Comment by todouu** [comment]
OK, I think I got what you said, I just need make sure that I don't merger file by myself .
