### ISSUE TITLE
Explore using Boost for code portability

### ISSUE THREAD

**Issue by pop** [XZES40/CS-Capstone-Project#19]
[The Boost C++ utilities](http://www.boost.org/) claim to provide a lot of utilities that we can use to make our code portable across operating systems. We should explore using this instead of writing our own Cross-OS API.

**Comment by pop** [comment]
Specifically [Boost::Filesystem](http://www.boost.org/doc/libs/1_40_0/libs/filesystem/doc/index.htm) can be very useful.

**Comment by shathaway** [comment]
ICU, Xalan-C, Xerces-C have compile toolsets for platform independence.  I have committed code samples to Transformer/capstone that can be used for some basic API independence without the hastles of integrating BOOST into the integration.

**Comment by pop** [comment]
@shathaway While ICU, Xalan-C, and Xerces-C have platform independence I am concerned that we will carry out other operations, like simple file-system interaction, which may not be platform-independent.

I agree that Boost may be more that we need, but exploring some level of out-sourcing of the platform-independence problem may still be worth investigating.

**Comment by pop** [comment]
We will not be using Boost.
