### ISSUE TITLE
Decide on a name

### ISSUE THREAD

**Issue by pop** [XZES40/CS-Capstone-Project#4]
We need to create a name for a few reasons.  Let's propose some names @woaizj @zixunlu.

I propose:
- ESZ (from Shuai in email)
- XEZS (Similar, but added an X as is common for XML projects)

I will think of more, please comment with additional suggestions.

**Comment by todouu** [comment]
Do we create team name or project name?

**Comment by pop** [comment]
We create team name, it will probably be the project name as well.  Apache can change the project name if they do not like it once we are done, but they seem not to care for now.

**Comment by pop** [comment]
We have decided on the name XZES40. X + first initials + group number.
